In [4]:
import pandas as pd
cohort_file= '/labs/shahlab/projects/agataf/data/cohorts/pooled_cohorts/cohort/all_cohorts.csv'

df = pd.read_csv(cohort_file)

numbers = df.groupby(['study', 'grp']).count().person_id

means = (df
         .groupby(['grp'])
         .mean()
         .filter(['age', 'ascvd_10yr', 'censored_10yr', 'event_time_10yr'])
         .round(3)
         .reset_index()
        )

means_all = (df
             .assign(grp='all')
             .groupby(['grp'])
             .mean()
             .filter(['age', 'ascvd_10yr', 'censored_10yr', 'event_time_10yr'])
             .round(3)
             .reset_index()
            )


means = pd.concat([means, means_all]).reset_index()#.set_index(['grp']).sort_values(by='study')

counts = (df
          .groupby('grp')
          .count()
          .filter(['person_id'])
          .rename(columns={'person_id': 'n'})
          .reset_index()
          .append({'n': df.count().person_id, 'grp': 'all'}, ignore_index=True)
          .reset_index()
         )

(means.assign(counts=counts.n).filter(['grp', 'counts', 'age', 'ascvd_10yr', 'censored_10yr'])
 .rename(columns={'grp': 'group'})
 .assign(group = lambda x: x.group.map({1: 'Black women', 2: 'White women',
                                       3: 'Black men', 4: 'White men', 'all': 'all'}))
)

         group  counts     age  ascvd_10yr  censored_10yr
0  Black women    5354  55.506       0.056          0.100
1  White women    8765  57.146       0.060          0.062
2    Black men    3848  56.292       0.077          0.125
3    White men    7652  56.516       0.103          0.073
4          all   25619  56.487       0.075          0.083